package java_projects.demo.fxml.authentication;

import java_projects.demo.config.Config;
import java_projects.demo.domain.User;
import java_projects.demo.fxml.BaseController;
import java_projects.demo.fxml.NotificationPopups;
import java_projects.demo.fxml.scene_changer.HomepageSceneChanger;
import java_projects.demo.fxml.scene_changer.LoginRegisterSceneChanger;
import java_projects.demo.service.Services;
import java_projects.demo.utils.PasswordEncryption;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Hyperlink;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class LoginPageController extends BaseController {
    @FXML
    protected Button buttonLogin;
    @FXML
    private Hyperlink hyperlinkRegister;
    @FXML
    private TextField textFieldUsername;
    @FXML
    private PasswordField textFieldPassword;

    /**
     * A method that will manage the event when there is the login button pressed
     */
    @FXML
    protected void clickLogin() {
        Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
        String username = textFieldUsername.getText();
        String password = textFieldPassword.getText();
        try {
            User user = serviceUsers.getUserByUsername(username);
            if (user.getPassword().equals(PasswordEncryption.encrypt(password,
                    Config.getProperties().getProperty("salt"), Config.getProperties().getProperty("key")))) {
                System.out.println(user.getUsername() + " logged in!");
                HomepageSceneChanger.changeSceneToHomeFeed((Stage) buttonLogin.getScene().getWindow(), username, services);
            } else {
                throw new Exception("User not found!");
            }
        } catch (Exception e) {
            NotificationPopups.errorPopup(e.getMessage());
        }
    }

    /**
     * A method that will handle the event generated by pressing the register button
     */
    @FXML
    protected void clickRegister() {
        System.out.println("ClickRegister");
        try {
            Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
            LoginRegisterSceneChanger.changeSceneToRegister((Stage) hyperlinkRegister.getScene().getWindow(), services);
        } catch (Exception e) {
            NotificationPopups.errorPopup(e.getMessage());
        }
    }
}
