salt=BkDOU6uSJrc5XuRu9OJBpJCHe7JCE7ZQ4bZPEke3pBEo5vVHgNF50i7HMIlIQjsVyb40Hh4BKInqs1AXnfPuM1cAZLEJDRpR8imR
key=my_very_strong_password
logoPath=/java_projects/demo/pictures/logo.png
incomingMessageColor=#87CEFA
sendingMessageColor=#E7FEFF
seenMessage=#00FF7F
username=postgres
password=postgres
databaseUrl=jdbc:postgresql://localhost:5432/ChitChatChainDB