package java_projects.demo.fxml.homepage;

import java_projects.demo.domain.Message;
import java_projects.demo.fxml.BaseController;
import java_projects.demo.fxml.NotificationPopups;
import java_projects.demo.fxml.scene_changer.HomepageSceneChanger;
import java_projects.demo.fxml.scene_changer.LoginRegisterSceneChanger;
import java_projects.demo.service.Services;
import java_projects.demo.utils.events.EventType;
import java_projects.demo.utils.events.MessageEvent;
import java_projects.demo.utils.events.UsersEvent;
import java_projects.demo.utils.observer.ObserverId;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.util.Objects;

public abstract class MainController extends BaseController implements ObserverId<UsersEvent<String>, String> {
    protected String username;

    public void setButtonMessagesState(boolean pendingMessage) {
        if (pendingMessage)
            buttonMessages.setId("main_button_highlighted");
        else
            buttonMessages.setId("main_button");
    }

    public void setUsername(String username) {
        this.username = username;
        this.serviceMessages.getLastMessageFromEveryConversation(this.username).forEach(message -> {
            if (message.getReceiver().equals(this.username))
                if (!message.isReceived()) {
                    this.serviceMessages.setMessagesReceived(message);
                    setButtonMessagesState(true);
                }
        });
    }

    public String getUsername() {
        return this.username;
    }

    @FXML
    protected Button buttonHome;
    @FXML
    protected Button buttonLogout;
    @FXML
    protected Button buttonSearch;
    @FXML
    protected Button buttonNotification;
    @FXML
    protected Button buttonProfile;
    @FXML
    protected Button buttonMessages;

    /**
     * A method that will handle the event generated by pressing the home button
     */
    @FXML
    protected void clickHome() {
        //changeSceneToHome(idUser, buttonHome, this);
    }

    protected void removeThisFromObservers() {
        serviceFriendships.removeObserver(this.username);
        serviceMessages.removeObserver(this.username);
    }

    /**
     * A method that will handle the event generated by pressing the logout button
     */
    @FXML
    protected void clickLogout() {
        System.out.println("LogoutClick");
        try {
            Stage stage = (Stage) buttonLogout.getScene().getWindow();
            Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
            removeThisFromObservers();
            LoginRegisterSceneChanger.changeSceneToLogin(stage, services);
        } catch (Exception e) {
            NotificationPopups.errorPopup(e.getMessage());
        }
    }

    /**
     * A method that will handle the event generated by pressing the search button
     */
    @FXML
    protected void clickSearch() {
        try {
            Stage stage = (Stage) buttonSearch.getScene().getWindow();
            Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
            removeThisFromObservers();
            HomepageSceneChanger.changeSceneToHomeSearch(stage, username, services);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            NotificationPopups.errorPopup(e.getMessage());
        }
    }

    /**
     * A method that will handle the event generated by pressing the notification button
     */
    @FXML
    public void clickNotification() {
        try {
            Stage stage = (Stage) buttonSearch.getScene().getWindow();
            Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
            removeThisFromObservers();
            HomepageSceneChanger.changeSceneToHomeNotifications(stage, username, services);
        } catch (Exception e) {
            NotificationPopups.errorPopup(e.getMessage());
        }
    }

    @FXML
    public void clickMessages() {
        try {
            Stage stage = (Stage) buttonSearch.getScene().getWindow();
            Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
            removeThisFromObservers();
            HomepageSceneChanger.changeSceneToHomeInbox(stage, username, null, services);
        } catch (Exception e) {
            NotificationPopups.errorPopup(e.getMessage());
        }
    }

    @FXML
    public void clickProfile() {
        try {
            Stage stage = (Stage) buttonProfile.getScene().getWindow();
            Services services = new Services(serviceUsers, serviceFriendships, serviceMessages);
            removeThisFromObservers();
            HomepageSceneChanger.changeSceneToHomeProfile(stage, username, username, services);
        } catch (Exception e) {
            e.printStackTrace();
            NotificationPopups.errorPopup(e.getMessage());
        }
    }

    @Override
    public void update(UsersEvent<String> event) {

    }

    @Override
    public void updateMessages(UsersEvent<String> event) {
        MessageEvent messageEvent = (MessageEvent) event;
        if (event.getTypeOfEvent() == EventType.ADD) {
            Message message = messageEvent.getNewMessage();
            if (Objects.equals(message.getReceiver(), this.username)) {
                this.buttonMessages.setId("main_button_highlighted");
                this.serviceMessages.setMessagesReceived(message);
            }
        }
    }

    @Override
    public void updateFriendships(UsersEvent<String> event) {

    }

}
